### ISSUE TITLE
Errors when `.Values.monolith.zoneAwareReplication` is false

### ISSUE THREAD

**Issue by raffraffraff** [NGDATA/mimir#1]
#### Describe the bug
If I turn off `.Values.monolith.zoneAwareReplication`, the helm chart fails to install because several components continue to use zoneAwareReplication. Each one has to be hunted down and explicitly turned off.

#### To Reproduce

1. Clone this repo
2. `cd operations/helm/charts/`
3. `helm install --values test.yaml mimir-distributed`

Use the following `test.yaml` file:
```
monolithic:
  zoneAwareReplication:
    enabled: false
```

I get this error:
```
Error: execution error at (mimir-distributed/templates/validate.yaml:153:4): You have set ingester.zoneAwareReplication.enabled=true. The mimir.config must include ingester.ring.zone_awareness_enabled=true. Please merge the latest mimir.config from the chart with your mimir.config.
```

#### Expected behavior
I expect that turning off `monolithic.zoneAwareReplication` will disable zoneAwareReplication across all components, and bypass validators that should only apply when zoneAwareReplication is enabled.

#### Environment

- Infrastructure: EKS, 2x Availability Zones
- Deployment tool: helm

#### Additional Context

See this comment: https://github.com/grafana/mimir/pull/4858#issuecomment-1661949279

A monolithic deployment is perfect for smaller 'development' clusters that may not have the requirements for zoneAwareReplication (such as 3 availability zones) or may not want replication, or may wish to reduce cloud costs by limiting cross-zone traffic. It should be simple to turn this feature off in one place and have all components honor it.

#### Suggestion: add "common" config

I have seen a number of helm charts that support the idea of a "common" set of configs that can be reused across sub-charts or components. Since zoneAwareReplication has a number of environment-specific settings such as zone name, region etc, it would be nice to define this _once only_ in a section like this:

```
common:
  zoneAwareReplication:
    enabled: true
    topologyKey: topology.kubernetes.io/zone
    zones:
    - name: eu-west-1c
      nodeSelector:
        topology.kubernetes.io/zone: eu-west-1c
    - name: eu-west-1b
      nodeSelector:
        topology.kubernetes.io/zone: eu-west-1b
    - name: eu-west-1c
      nodeSelector:
        topology.kubernetes.io/zone: eu-west-1c
```

**Comment by rubenvw-ngdata** [comment]
Very sorry for the late answer on this issue

Are you sure that you used the latest version of the chart.
I have recently run mimir on a single monolithic node with this configuration and that worked:
```
deploymentMode: monolithic
...
monolithic:
  replicas: 1
...
  zoneAwareReplication:
    enabled: false
  extraArgs:
    ingester.ring.replication-factor: 1
```
the validation the code is
```
   and
     (or
       (and (eq .Values.deploymentMode "microservices") .Values.ingester.zoneAwareReplication.enabled)
       (and (eq .Values.deploymentMode "monolithic") .Values.monolithic.zoneAwareReplication.enabled))
     (not ((($calculatedConfig).ingester).ring).zone_awareness_enabled)
```
are you sure that you have set the deploymentMode to monolithic
