### ISSUE TITLE
Provide ingress example for monolithic deployment

### ISSUE THREAD

**Issue by mi-fabien-cayre** [NGDATA/mimir#2]
Using the Ingress kubernetes ressources with monolithic deployment mode doesn't correctly redirect to the monolithic headless svc, I had to change ingress values to make it works.

It could be interesting to add this in the  monolithic values example file.

I had to overwrite the values like this to get it working btw.
```yaml
ingress:
      enabled: true
      paths:
        distributor-headless: []
        alertmanager-headless: []
        ruler: []
        query-frontend: []
        compactor: []
        monolithic-headless:
          - path: /distributor
          - path: /api/v1/push
          - path: /otlp/v1/metrics
          - path: /alertmanager
          - path: /multitenant_alertmanager/status
          - path: /api/v1/alerts
          - path: /prometheus/config/v1/rules
          - path: /prometheus/api/v1/rules
          - path: /prometheus/api/v1/alerts
          - path: /prometheus
          - path: /api/v1/status/buildinfo
          - path: /api/v1/upload/block/
```
